project_id = "ohafipcsokgxmxmknfom"

[functions.transactions]
verify_jwt = true

[functions.ai-analyze]
verify_jwt = true

[functions.dashboard]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.market-data]
verify_jwt = true

[functions.fetch-news]
verify_jwt = false

[functions.currency-converter]
verify_jwt = false

[functions.ai-suggest-transaction]
verify_jwt = true

[functions.track-activity]
verify_jwt = true
